//! MCP server (hello-world).
//!
//! Mounts an MCP streamable-HTTP transport at /mcp on the main axum
//! listener. MCP clients speak the Model Context Protocol here; the rest
//! of the server continues to serve the dashboard REST/WS API.

use std::sync::Arc;

use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::router::tool::ToolRouter,
    model::{
        CallToolResult, Content, Implementation, ProtocolVersion, ServerCapabilities, ServerInfo,
    },
    tool, tool_handler, tool_router,
    transport::streamable_http_server::{
        StreamableHttpServerConfig, StreamableHttpService, session::local::LocalSessionManager,
    },
};

#[derive(Clone)]
pub struct OrchestrAiMcp {
    // Consumed by code generated by #[tool_handler], which dead-code analysis
    // doesn't trace through the macro boundary.
    #[allow(dead_code)]
    tool_router: ToolRouter<OrchestrAiMcp>,
}

#[tool_router]
impl OrchestrAiMcp {
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    #[tool(description = "Return a greeting from the orchestrAI MCP server")]
    fn hello(&self) -> Result<CallToolResult, McpError> {
        Ok(CallToolResult::success(vec![Content::text(
            "hello from orchestrAI",
        )]))
    }
}

impl Default for OrchestrAiMcp {
    fn default() -> Self {
        Self::new()
    }
}

#[tool_handler]
impl ServerHandler for OrchestrAiMcp {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::from_build_env())
            .with_protocol_version(ProtocolVersion::V_2024_11_05)
            .with_instructions(
                "orchestrAI MCP server. Tools: hello (returns a greeting).".to_string(),
            )
    }
}

pub type McpService = StreamableHttpService<OrchestrAiMcp, LocalSessionManager>;

pub fn build_service() -> McpService {
    StreamableHttpService::new(
        || Ok(OrchestrAiMcp::new()),
        Arc::new(LocalSessionManager::default()),
        StreamableHttpServerConfig::default(),
    )
}
