//! MCP server (hello-world).
//!
//! Same handler, two transports:
//! - `StreamableHttpService` mounted on the main axum listener at `/mcp`
//!   (see [`transport::build_http_service`]); MCP clients that speak HTTP/SSE
//!   (e.g. the MCP Inspector in remote mode) connect here.
//! - stdin/stdout via [`transport::run_stdio`], dispatched from the
//!   `orchestrai-server mcp` subcommand; MCP clients that spawn the server
//!   as a child process (e.g. Claude Code) connect here.

pub mod transport;

use rmcp::{
    ErrorData as McpError, ServerHandler,
    handler::server::router::tool::ToolRouter,
    model::{
        CallToolResult, Content, Implementation, ProtocolVersion, ServerCapabilities, ServerInfo,
    },
    tool, tool_handler, tool_router,
};

#[derive(Clone)]
pub struct OrchestrAiMcp {
    // Consumed by code generated by #[tool_handler], which dead-code analysis
    // doesn't trace through the macro boundary.
    #[allow(dead_code)]
    tool_router: ToolRouter<OrchestrAiMcp>,
}

#[tool_router]
impl OrchestrAiMcp {
    pub fn new() -> Self {
        Self {
            tool_router: Self::tool_router(),
        }
    }

    #[tool(description = "Return a greeting from the orchestrAI MCP server")]
    fn hello(&self) -> Result<CallToolResult, McpError> {
        Ok(CallToolResult::success(vec![Content::text(
            "hello from orchestrAI",
        )]))
    }
}

impl Default for OrchestrAiMcp {
    fn default() -> Self {
        Self::new()
    }
}

#[tool_handler]
impl ServerHandler for OrchestrAiMcp {
    fn get_info(&self) -> ServerInfo {
        ServerInfo::new(ServerCapabilities::builder().enable_tools().build())
            .with_server_info(Implementation::from_build_env())
            .with_protocol_version(ProtocolVersion::V_2024_11_05)
            .with_instructions(
                "orchestrAI MCP server. Tools: hello (returns a greeting).".to_string(),
            )
    }
}
